version: '3.9'

services:
  # Quizzify API
  quizzify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizzify-api
    command: uvicorn quizzify.main:app --reload --host 0.0.0.0 --port 8000 --log-config quizzify/logging.conf
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - quizzify-api

  ## -----------------------------------------------------------------------------------
  ## ------------------------------------- Database ------------------------------------
  ## -----------------------------------------------------------------------------------

  # PostgreSQL
  db:
    image: postgres:16
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      # Mount the volume to persist the data
      # - postgres-data:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data
      # Mount the init script to create the database as an entrypoint to the container
      - ./app/quizzify/databases/:/docker-entrypoint-initdb.d/
#      - ./app/quizzify/databases/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quizzify-api

# Volumes
volumes:
  # PostgreSQL
  postgres-data:
      driver: local

# Networks
networks:
  quizzify-api:
    driver: bridge
