version: '3.9'

services:
  # Quizzify API
  quizzify-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizzify-api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --log-config logging.conf
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - postgres
    env_file:
      - .env

  ## -----------------------------------------------------------------------------------
  ## ------------------------------------ Databases ------------------------------------
  ## -----------------------------------------------------------------------------------

  # PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      # Mount the volume to persist the data
      - postgres_data:/var/lib/postgresql/data
      # Mount the init script to create the database as an entrypoint to the container
      - ./app/quizzify/databases/init.sql:/docker-entrypoint-initdb.d/init.sql

  # MongoDB
  mongodb:
    image: mongo:7.0.5
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

# Volumes
volumes:
  # PostgreSQL
  postgres_data:
      driver: local

  # MongoDB
  mongodb_data:
    driver: local
